version: '3.8'

services:
  web-backend:
    build: ./brandgenie-pro-web/backend
    ports:
      - "8001:8001"
    volumes:
      - ./brandgenie-pro-web/backend:/app
    environment:
      - DATABASE_URL=postgresql://postgres:THD111@web-db:5432/onebuttonapp
    depends_on:
      - web-db

  mobile-backend:
    build: ./brandgenie-pro-mobile/backend
    ports:
      - "8000:8000"
    volumes:
      - ./brandgenie-pro-mobile/backend:/app
    environment:
      - DATABASE_URL=postgresql://postgres:THD111@mobile-db:5432/onebuttonapp
    depends_on:
      - mobile-db

  web-frontend:
    build: ./brandgenie-pro-web/frontend
    ports:
      - "5173:5173"
    working_dir: /app
    command: ["npm", "run", "dev", "--", "--host", "0.0.0.0"]
    # volumes:
    #   - ./brandgenie-pro-web/frontend:/app
    depends_on:
      - web-backend

  mobile-frontend:
  build: ./brandgenie-pro-mobile/frontend
  ports:
    - "5174:5174"
  working_dir: /app
  command: ["npx", "expo", "start", "--port", "5174", "--host", "0.0.0.0"]
  depends_on:
    - mobile-backend



  web-db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: THD111
      POSTGRES_DB: onebuttonapp
    volumes:
      - ./brandgenie-pro-web/backend/database/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5433:5432"

  mobile-db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: THD111
      POSTGRES_DB: onebuttonapp
    volumes:
      - ./brandgenie-pro-mobile/backend/database/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5434:5432"
