# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure App Service: https://aka.ms/python-webapps-actions

name: Build and deploy Dockerized backend to Azure Web App - brandgenie-backend

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_695F1C901D51401381071E992DF99FE2 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_3A5FFE40CE7C4E4EA3E7662534106724 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_8B76C17BA5E243FEAC214682E9749F19 }}

      - name: Log in to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: brandgenieacr.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build and Push Docker image (backend)
        run: |
          docker build -t brandgenieacr.azurecr.io/backend:latest ./backend
          docker push brandgenieacr.azurecr.io/backend:latest

      - name: Deploy to Azure Web App (backend)
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'brandgenie-backend'
          images: 'brandgenieacr.azurecr.io/backend:latest'
